showNames: true #show names of columns in first row, defaults to false
crlf: true #use windows crlf instead of linux lf, defaults to false

# Connection:
host: localhost #defaults to "localhost"
port: 3306 #defaults to 3306
username: root #defaults to "root"
password:  #defaults to ""(nothing)
